packages:
  - designer
  - custom-plugins/*
  - materials
allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
  vue-demi: set this to true or false
patchedDependencies:
  '@opentiny/tiny-engine-canvas': patches/@opentiny__tiny-engine-canvas.patch
  '@opentiny/tiny-engine-common': patches/@opentiny__tiny-engine-common.patch
