packages:
  - designer
  - custom-plugins/*
  - materials
allowBuilds:
  core-js: true
  esbuild: true
  vue-demi: true
patchedDependencies:
  '@opentiny/tiny-engine-canvas': patches/@opentiny__tiny-engine-canvas.patch
  '@opentiny/tiny-engine-common': patches/@opentiny__tiny-engine-common.patch
  '@opentiny/tiny-engine-plugin-materials@2.10.0': patches/@opentiny__tiny-engine-plugin-materials@2.10.0.patch
